# Welcome to Jekyll!
#
# This config file contains settings that affect your entire site. Customize
# these options to suit the needs of your IT Infrastructure blog.
#
# For assistance with YAML syntax, visit:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# Personalize your blog using the variables below, accessible in your
# templates via {{ site.title }}, {{ site.email }}, and others.

title: IT Infrastructure Insights
email: contact@itinfra-blog.com
description: >-
  Stay updated with the latest trends, best practices, and deep dives into IT infrastructure, cloud computing, networking, and security.
baseurl: "" # Example: /blog for a subpath
url: "http://www.itinfra-blog.com" # Your domain name with protocol
twitter_username: itinfra_tweets
github_username: itinfra-hub

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

# SEO and Sitemap settings
seo:
  title: "IT Infrastructure Insights"
  description: "Comprehensive insights into IT infrastructure, cloud technologies, and system architecture."
  author: "Your Name"

sitemap:
  exclude:
    - "/404.html"

# Navigation settings
nav:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

# Social media
social_links:
  twitter: "https://twitter.com/itinfra_tweets"
  github: "https://github.com/itinfra-hub"
  linkedin: "https://www.linkedin.com/company/itinfra"

# Exclude unnecessary directories and files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - Gemfile.lock

# Include additional directories
include:
  - _pages
  - _posts